apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IuZWNvbW1lcmNlLmNvcnAiOnsidXNlcm5hbWUiOiJrOHMtcHVsbGVyIiwicGFzc3dvcmQiOiIhMXEydzNlNHJSIiwiZW1haWwiOiJub25lIiwiYXV0aCI6Ims4cy1wdWxsZXI6ITEwcTJ3M2U0clIifX19
