# backend-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: my-backend
  template:
    metadata:
      labels:
        app: my-backend
    spec:
      containers:
      - name: my-backend-container
        # 이미지 이름만 명시 (태그는 overlay에서 지정)
        image: 224874704033.dkr.ecr.ap-northeast-2.amazonaws.com/my-backend
        env:
        - name: ALLOWED_ORIGIN
          value: "*"
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            # 시크릿 이름도 overlay에서 prefix가 붙을 것을 예상하여 기본 이름만 명시
            name: backend-db-secret
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi