apiVersion: apps/v1
kind: Deployment
metadata:
  # Kustomize가 namespace를 나중에 추가하므로 여기서는 생략합니다.
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: my-backend
  template:
    metadata:
      labels:
        app: my-backend
      annotations:   # Envoy 사이드카의 네트워크 지표
        prometheus.io/scrape: "true"
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15090"
    spec:
      containers:
      - name: my-backend-container
        # image 태그는 overlays에서 최종적으로 지정되므로, base에서는 초기 버전이나 latest를 사용합니다.
        image: 224874704033.dkr.ecr.ap-northeast-2.amazonaws.com/my-backend:1.0
        ports:
        - containerPort: 8080
        env:
        - name: ALLOWED_ORIGIN
          value: "*"
        envFrom:
        - secretRef:
            # Secret의 이름은 환경에 따라 달라지지 않으므로 base에 명시합니다.
            name: backend-db-secret
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
