apiVersion: v1
kind: Service
metadata:
  name: backend-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /api/products
spec:
  selector:
    app: my-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP